name: pitch_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.0
  flutter_facebook_auth: ^7.0.1
  buttons_tabbar: ^1.3.13
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.2
  date_picker_timeline: ^1.2.5
  dio: ^5.4.0
  firebase_auth: ^5.1.1
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.0
  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  lottie: ^3.0.0
  otp_text_field: ^1.1.3
  pinput: ^5.0.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.0
  flutter_meta_sdk: ^1.0.2
  cached_network_image: ^3.3.1
  email_otp: ^3.0.1
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  twitter_login: ^4.4.2
  crypto: ^3.0.3
  sign_in_button: ^3.2.0
  emailjs: ^4.0.0
  get: ^4.6.6
  firebase_messaging: ^15.0.4
  firebase_analytics: ^11.2.1
  googleapis_auth: ^1.6.0
  fluttertoast: ^8.2.6
  oauth2: ^2.0.2
  flutter_email_sender: ^6.0.3
  flutter_localization: ^0.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
