// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,      
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_RDNCdbmzDnIi6uML9Ktv1lORZ-ymoUI',
    appId: '1:600696752875:web:2af1131ee773bf43c2ccae',
    messagingSenderId: '600696752875',
    projectId: 'pitch-test-12b39',
    authDomain: 'pitch-test-12b39.firebaseapp.com',
    storageBucket: 'pitch-test-12b39.appspot.com',
    measurementId: 'G-YJ1HGCDMZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADnkmVUgl3YaXMRTh4oczWwGlFitW3_hU',
    appId: '1:600696752875:android:4a6eaba821a3011bc2ccae',
    messagingSenderId: '600696752875',
    projectId: 'pitch-test-12b39',
    storageBucket: 'pitch-test-12b39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASsqNgifrWpcqdqPcVJSgqZu20Pv_U0OU',
    appId: '1:600696752875:ios:6f174d44138b7c28c2ccae',
    messagingSenderId: '600696752875',
    projectId: 'pitch-test-12b39',
    storageBucket: 'pitch-test-12b39.appspot.com',
    androidClientId: '600696752875-ci9okn80pc8hmc07bidm40p44n9fnm6a.apps.googleusercontent.com',
    iosClientId: '600696752875-eov3jaho163h747c1t1pgd0o43hqjnpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.pitchTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASsqNgifrWpcqdqPcVJSgqZu20Pv_U0OU',
    appId: '1:600696752875:ios:6f174d44138b7c28c2ccae',
    messagingSenderId: '600696752875',
    projectId: 'pitch-test-12b39',
    storageBucket: 'pitch-test-12b39.appspot.com',
    androidClientId: '600696752875-ci9okn80pc8hmc07bidm40p44n9fnm6a.apps.googleusercontent.com',
    iosClientId: '600696752875-eov3jaho163h747c1t1pgd0o43hqjnpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.pitchTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_RDNCdbmzDnIi6uML9Ktv1lORZ-ymoUI',
    appId: '1:600696752875:web:9383992d23612f45c2ccae',
    messagingSenderId: '600696752875',
    projectId: 'pitch-test-12b39',
    authDomain: 'pitch-test-12b39.firebaseapp.com',
    storageBucket: 'pitch-test-12b39.appspot.com',
    measurementId: 'G-JGKLTH2W1E',
  );
}
